[package]
name = "dw-systest"
version = "0.1.0"
authors = ["Steven Fackler <sfackler@gmail.com>"]
edition = "2018"

[dependencies]
dw-sys = { path = "../dw-sys" }
libc = "0.2"

[build-dependencies]
ctest2 = "0.4"
