[package]
name = "unwind-systest"
version = "0.1.0"
authors = ["Steven Fackler <sfackler@palantir.com>"]
edition = "2018"

[features]
ptrace = ["unwind-sys/ptrace"]

[dependencies]
unwind-sys = { path = "../unwind-sys" }
libc = "0.2"

[build-dependencies]
ctest2 = "0.4"
